### ISSUE TITLE
Sign-up throwing Errors

### ISSUE THREAD

**Issue by vasuvius** [nathan-149/CustomCrypocurrency#15]
Got port 80 running after running python3 run.py (using python 3.7) and installing all dependencies. On Register after clicking sign-up I get "Internal Server Error. The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

In terminal:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x1094c5e08 (otid=0x109557d38) current active started main>

AND:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 914, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute

all dependencies are pip installed for python3. 

Wondering how I can fix this issue for sign-up!

**Comment by vasuvius** [comment]
https://stackoverflow.com/questions/66647787/cannot-connect-to-sqlite-database-with-flask-sqlalchemy

The issue was with SQLAlchemy v 1.4.0 that screws up URL objects. Fixed sign-up
