### ISSUE TITLE
Can't register in web app. 

### ISSUE THREAD

**Issue by NewtonJr4108** [nathan-149/CustomCrypocurrency#26]
Gives 500 Internal Server Error. 

In run.py terminal, it gives this error:
______________________________________________________________________________________________________________________________________
[2021-05-23 16:59:58,636] ERROR in app: Exception on /register [POST]
Traceback (most recent call last):
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\sqlalchemy\util\_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x000002C09A291510 (otid=0x000002C09BC475C0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Coding\OneDrive\Desktop\CustomCrypocurrency\gymcoin\routes.py", line 60, in register
    if form.validate_on_submit():
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask_wtf\form.py", line 100, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\wtforms\form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\wtforms\form.py", line 150, in validate
    if not field.validate(self, extra):
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\wtforms\fields\core.py", line 226, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\wtforms\fields\core.py", line 246, in _run_validation_chain
    validator(form, self)
  File "C:\Users\Coding\OneDrive\Desktop\CustomCrypocurrency\gymcoin\forms.py", line 28, in validate_username
    user = User.query.filter_by(username = username.data).first()
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\sqlalchemy\orm\scoping.py", line 129, in __call__
    return self.registry()
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\sqlalchemy\util\_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\sqlalchemy\orm\session.py", line 4065, in __call__
    return self.class_(**local_kw)
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 998, in engine
    return self.get_engine()
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\sqlalchemy\util\deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\sqlalchemy\engine\create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\site-packages\sqlalchemy\dialects\sqlite\pysqlite.py", line 473, in dbapi
    from sqlite3 import dbapi2 as sqlite
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "\\LAPTOP-DF7SK2QD\Users\Coding\anaconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.
127.0.0.1 - - [23/May/2021 16:59:58] "←[35m←[1mPOST /register HTTP/1.1←[0m" 500 -
______________________________________________________________________________________________________________________________________
Help would be appreciated.

**Comment by NTechStorm** [comment]
"ImportError: DLL load failed while importing _sqlite3: The specified module could not be found."

Change the import _sqlite3 to import sqlalchemy. If that doesn't work try to do import sqlite plain and simple. Have a nice day.

**Comment by gptshubham595** [comment]
copy sqlite.dll 


Try copying the sqlite3.dll from the

C:\Users\YOURUSER\anaconda3\Library\bin

folder to

C:\Users\YOURUSER\Anaconda3\DLLs

**Comment by Mohnish2004** [comment]
Hey, can anyone please clarify in helping fix this while registering

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
